version: '3.7'

services:
  app:
    build: .
    container_name: laravelapp
    ports:
      - "8080:8000"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db_1
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "restful"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: